sonar.projectKey=Estadio-do-Dragao-app_Fanapp
sonar.organization=fanapp-estadio-dragao

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Fanapp Interface
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=lib
sonar.tests=test,integration_test

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Coverage report path
sonar.dart.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,lib/generated/**,lib/features/map/presentation/widgets/stadium_painter.dart
